// Generated by CoffeeScript 1.7.1
var boundingBox, canvasHeight, canvasWidth, createVis, dataset, margin, svg;

margin = {
  top: 50,
  bottom: 50,
  left: 50,
  right: 50
};

canvasWidth = 960 - margin.left - margin.right;

canvasHeight = 300 - margin.top - margin.bottom;

svg = d3.select("#vis").append("svg").attr("width", canvasWidth + margin.left + margin.right).attr("height", canvasHeight + margin.top + margin.top).append("g").attr("transform", "translate(" + margin.left + ", " + margin.top + ")");

boundingBox = {
  x: 100,
  y: 10,
  width: canvasWidth - 100,
  height: 100
};

dataset = [];

createVis = function() {
  var visFrame, xScale;
  xScale = d3.scale.linear().domain([0, 100]).range([0, boundingBox.width]);
  visFrame = svg.append("g").attr("transform", "translate(" + boundingBox.x + ", " + (boundingBox.y + boundingBox.height) + ")");
  return visFrame.append("rect");
};

d3.csv("dataExportWiki.csv", function(data) {
  return createVis();
});
